export const userData = [
    {
      name: "Jan",
      "Active User": 4000,
    },
    {
      name: "Feb",
      "Active User": 3000,
    },
    {
      name: "Mar",
      "Active User": 2000,
    },
    {
      name: "Apr",
      "Active User": 2780,
    },
    {
      name: "May",
      "Active User": 1890,
    },
    {
      name: "Jun",
      "Active User": 2390,
    },
    {
      name: "Jul",
      "Active User": 3490,
    },
    {
      name: "Aug",
      "Active User": 3000,
    },
    {
      name: "Seb",
      "Active User": 2390,
    },
    {
      name: "Oct",
      "Active User": 2780,
    },
    {
      name: "Nov",
      "Active User": 2000,
    },
    {
      name: "Dec",
      "Active User": 3490,
    },
  ];

export const userRows = [
    {
      id: 1,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 2,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 3,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 4,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 5,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 6,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 7,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 8,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 9,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 10,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 11,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 12,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 13,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 14,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 15,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 16,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 17,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 18,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 19,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
    {
      id: 20,
      userName: "Jon Snow",
      avatar: "https://source.unsplash.com/random",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00",
    },
  ];

  export const productRows = [
    {
      id: 1,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 2,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 3,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 4,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 5,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 6,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 7,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 8,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 9,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 10,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 11,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 12,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 13,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 14,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 15,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 16,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 17,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 18,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 19,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 20,
      name: "Apple Airpods",
      avatar: "https://source.unsplash.com/random",
      stock: 123,
      status: "active",
      price: "$120.00",
    },
  ];